spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: techservice
    password: techservice
#    data: classpath*:import.sql
  jpa:
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 9090
diski:
  clientId: fooClientIdPassword
  clientSecret: secret
  signingKey: 123